# filename: /src/stubs/win32clipboard.pyi

CF_UNICODETEXT: int

def OpenClipboard(*args, **kwargs) -> None: ...
def EmptyClipboard() -> None: ...
def SetClipboardText(
    text: str,
    format: int = ...,
) -> None: ...
def CloseClipboard() -> None: ...